---
format:
  gfm:
    html-math-method: webtex
---

## Overview

Finding resources on the mathematical aspects of the generalized linear model is challenging for a few reasons.

-   Many resources talk about some families, but not others. Inverse Gaussian and Negative binomial are usually left out.
-   Only some formulas are stated while others are not. Common example is how to calculate $\phi$ in terms of the pdf's or pmf's parameters.
-   Some formulas drop constant's because they do not affect optimization in the IRWLS algorithm.
-   The starting pdf is assumed known and not stated. For the gamma distribution, the starting pdf has a unique parameterization.

The goal of this document is to address these problems by clearly stating **all** formulas for **all** families in a consistent order. No proofs. Minimal words. All the necessary pieces.

## Exponential Form and Formula Overview

When deriving generalized linear models, the probability density or probability mass function is algebraically manipulated into the exponential form. The idea is to start with a formula for the pdf of a distribution. For example,

$$ f(y; \mu, \sigma^2) = \frac{1}{\sqrt{2\pi\sigma^2}} exp(-\frac{(y - \mu)^2}{2\sigma^2}) $$ and change it to an equivalent exponential form

$$ f(y; \mu, \sigma^2) = exp(\frac{y\mu-\mu^2/2}{\sigma^2} - \frac{y^2}{2\sigma^2} - \frac{1}{2}ln(2\pi\sigma^2)) $$

Then define functions a, b, and c so the specific exponential form is a special case of the general exponential form

$$ f(y; \theta, \phi) = exp(\frac{y\theta - b(\theta)}{a(\phi)} + c(y,\phi))$$The general exponential form is the form optimized by the IRWLS algorithm. Note f started as a function of $\mu$ and $\sigma^2$ and ended as a function of $\theta$ and $\phi$. In addition to specifying a, b, and c, functions to calculate $\theta$ and $\phi$ are required.

## The Gaussian Family

The usual pdf is

$$ f(y; \mu, \sigma^2) = \frac{1}{\sqrt{2\pi\sigma^2}} exp(-\frac{(y - \mu)^2}{2\sigma^2}) $$

In exponential form, the pdf is

$$ f(y; \mu, \sigma^2) = exp(\frac{y\mu-\mu^2/2}{\sigma^2} - \frac{y^2}{2\sigma^2} - \frac{1}{2}ln(2\pi\sigma^2)) $$

By inspection:

$$ \theta = \mu $$ $$ \phi = \sigma^2 $$ $$ a(\phi) = \phi $$ $$ b(\theta) = \theta^2/2 $$ $$ c(y, \phi) = - \frac{y^2}{2\phi} -\frac{1}{2}ln(2\pi\phi) $$

## The Gamma Family

This distribution is usually parameterized by shape and rate. For the generalized linear models framework, this pdf is parameterized by $\mu$ and $\phi$

$$ f(y; \mu, \phi) = \frac{1}{y\Gamma(\frac{1}{\phi})} (\frac{y}{\mu\phi})^\frac{1}{\phi} exp(-\frac{y}{\mu\phi})$$

In exponential form, the pdf is

$$ f(y; \mu, \phi) = exp(\frac{\frac{y}{\mu} - (-ln(\mu))}{-\phi} + \frac{1-\phi}{\phi}ln(y) - \frac{ln(\phi)}{\phi} - ln{\Gamma(\frac{1}{\phi})})   $$

By inspection:

$$ \theta = \frac{1}{\mu} $$ $$ \phi = \phi $$ $$ a(\phi) = -\phi $$ $$ b(\theta) = -ln(\frac{1}{\theta}) $$ $$ c(y, \phi) = \frac{1-\phi}{\phi}ln(y) - \frac{ln(\phi)}{\phi} - ln{\Gamma(\frac{1}{\phi})} $$

## The Inverse Gaussian Family

The usual pdf is

$$ f(y; \mu, \sigma^2) = \frac{1}{\sqrt{2\pi y^3 \sigma^2}} exp(-\frac{(y - \mu)^2}{2(\mu\sigma)^2y}) $$

In exponential form, the pdf is

$$ f(y; \mu, \sigma^2) = exp(\frac{\frac{y}{2\mu^2} - \frac{1}{\mu}}{-\sigma^2} + \frac{1}{-2y\sigma^2} - \frac{1}{2}ln(2\pi y^3 \sigma^2)) $$

By inspection:

$$ \theta = \frac{1}{2\mu^2} $$ $$ \phi = \sigma^2 $$ $$ a(\phi) = -\phi $$ $$ b(\theta) = \sqrt{2*\theta} $$ $$ c(y, \phi) = \frac{1}{-2y\phi} - \frac{1}{2}ln(2\pi y^3 \phi)) $$

## The Binomial Family

The usual pdf is

$$ f(y; n, p) = \binom{n}{y} p^y (1-p)^{n-y} $$

In exponential form, the pdf is

$$ f(y; n, p) = exp(y*ln(\frac{p}{1-p}) + n*ln(1-p) + ln\binom{n}{y}) $$

By inspection:

$$ \theta = ln(\frac{p}{1 - p}) $$ $$ \phi = 1 $$ $$ a(\phi) = \phi $$ $$ b(\theta) = n * ln(1 + exp(\theta)) $$ $$ c(y, \phi) =ln\binom{n}{y}$$

## The Poisson Family

The usual pdf is

$$ f(y; \mu) = \frac{exp(-\mu) * \mu^y}{y!}  $$

In exponential form, the pdf is

$$ f(y; \mu) = exp(y*ln(\mu) - \mu - ln\Gamma(y+1)) $$

By inspection:

$$ \theta = ln(\mu) $$ $$ \phi = 1 $$ $$ a(\phi) = \phi $$ $$ b(\theta) = exp(\theta) $$ $$ c(y, \phi) = -ln\Gamma(y+1))$$

## The Negative Binomial Family

The usual pdf is

$$ f(y; r, p) = \binom{y + r - 1}{r-1} p^r (1-p)^{y} $$

In exponential form, the pdf is

$$ f(y; r, p) = exp(y*ln(1-p) + r*ln(p) + ln\binom{y + r - 1}{r-1}) $$

By inspection:

$$ \theta = ln(1-p) $$ $$ \phi = 1 $$ $$ a(\phi) = \phi $$ $$ b(\theta) = - r * ln(1 - exp(\theta)) $$ $$ c(y, \phi) =ln\binom{y + r - 1}{r-1})$$

## Additional Resources

All formulas come out of Generalized Linear Models and Extensions by Hardin and Hilber.

See <https://github.com/gmcmacran/altForm> for working functions based on these equations.
